### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ben-Davis1**

### CODE REVIEW

**Comment by alexeygolev** [comment]
Smart:)

**Comment by Ben-Davis1** [comment]
I didn't have any good playlists so decided to piggy back of Sam's  :) 
That was right, yeah?

**Comment by alexeygolev** [comment]
Well the task wasn't about the music so yes))) You managed to create a pull request. It's a good start)

**Comment by alexeygolev** [comment]
[I want to add a tag to a new task](https://trello.com/c/9XEgVFsQ/5-i-want-to-add-a-tag-to-a-new-task)

**Pull request merged**
